services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sales_db
    ports:
      - "5432:5432"
    volumes:
      # This mounts the init script to be run on first startup
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      # This persists the database data on your local machine
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: